# docker-compose.metrics.yml

services:
  prometheus:
    image: prom/prometheus
    container_name: workbench-prometheus
    user: root
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=30d

    volumes:
      - prometheus_data:/prometheus
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - workbench-net

  node-exporter:
    image: prom/node-exporter
    container_name: workbench-node-exporter
    restart: unless-stopped

    command:
      - '--path.rootfs=/host'
    volumes:
      - '/:/host:ro,rslave'
    networks:
      - workbench-net

networks:
  workbench-net:
    external: true

volumes:
  prometheus_data: