{
 "title": "Peeppips",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Frontend",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container=\"workbench-nextjs-dev\"}"
    }
   ]
  },
  {
   "title": "Temporal Worker",
   "type": "logs",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{container=\"workbench-go-temporal-worker\"}"
    }
   ]
  },
  {
   "title": "Temporal Gateway / API Logs",
   "type": "logs",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "{container=~\".*temporal.*gateway.*|.*api.*gateway.*\"}"
    }
   ]
  },
  {
   "title": "Backend Server API",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "{container=~\".*server.*|backendworkbenchclient-server.*\"}"
    }
   ]
  },
  {
   "title": "MT5 Ingest Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "{container=~\".*mt5-ingest.*\"}"
    }
   ]
  },
  {
   "title": "Deriv Datasource Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "{container=~\".*deriv.*datasource.*\"}"
    }
   ]
  },
  {
   "title": "Temporal Server Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "{container=~\".*temporal$|.*temporal-server.*|workbench-temporal\"}"
    }
   ]
  }
 ]
}